config/routes.rb
Rails.application.routes.draw do

  # resources :meetings
  root 'team_roster#index'
  # resource :calendar, only: [:show], controller: :calendar
  # root to: "calendar#show"
  resources :team_roster  do 
    member do
      get :delete
    end
  end

  resources :calendar  do 
    member do
      get :delete
    end
  end

  resources :commitment  do 
    member do
      get :delete
    end
  end

  resources :event  do 
    member do
      get :delete
      get :name
    end
  end




  # resources :admin do
  #   member do
  #     get :delete
  #   end
  # end
 
  # get 'user/team_roster'
  # get 'user/calendar'
  # get 'user/commitment'
  # get 'user/event'
  # get 'user/new'
  # get 'admin/team_roster'
  # get 'admin/calendar'
  # get 'admin/commitment'
  # get 'admin/event'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commitment.rb
class Commitment < ApplicationRecord
    belongs_to :student
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :commitments
    has_many :students, through: :commitments
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :commitments
    has_many :events, through: :commitments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def team_roster
  end

  def calendar
  end

  def commitment
  end

  def event
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @student = Student.order('id ASC')
    start_date = params.fetch(:start_date, Date.today).to_date

    @meetings = Event.where(date_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash.notice = "Student created"
      redirect_to(team_roster_index_path)
    else
      render('new')
    end
  end

  def show
    # @student = Student.order('id ASC')
    start_date = params.fetch(:start_date, Date.today).to_date
    @student = Student.find(params[:id])
    @meetings = Event.where(starts_at: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash.notice = "Student updated"
      redirect_to(team_roster_path(@student))
    else
      render("edit")
    end
  end

  def delete
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(team_roster_index_path)
  end

  # def show
  #   @date = params[:date] ? Date.parse(params[:date]) : Date.today
  #
  #
  # end

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :class_year, :email, :phone)
    end



  end

app/controllers/commitment_controller.rb
class CommitmentController < ApplicationController
  def index
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.find(params[:id])
    @event = Event.all.first
    @events = Event.all
  end


  def create
    # puts student_params
    @event = Event.find(params[:event][:id])
    @student = Student.find(params[:event][:student_id])
    Commitment.create({student:@student, event:@event})
    # @events = Event.find(student_params)
    if @student.save
      flash.notice = "Student created"
      redirect_to(team_roster_index_path)
    else
      render('new')
    end
  end

  def show
    @student = Student.find(params[:id])
    @commitments = Commitment.where(student_id: @student.id)
  end

  def edit
    @commitment = Commitment.find(params[:id])
    @student = Student.find(@commitment.student_id)
    @event = Event.find(@commitment.event_id)
    @events = Event.all
  end

  def update
    @commitment = Commitment.find(params[:commitment][:commitment_id])
    @event = Event.find(params[:commitment][:id])
    if @commitment.update(:event_id => @event.id)
      flash.notice = "Commitment updated"
      redirect_to(team_roster_path)
    else
      render("edit")
    end
  end

  def delete
    @commitment = Commitment.find(params[:id])
    @student = Student.find(@commitment.student_id)
    @event = Event.find(@commitment.event_id)
  end

  def destroy
    puts params
    @commitment = Commitment.find(params[:commitment][:commitment_id])
    @commitment.destroy
    # @student = Student.find(params[:id])
    # @student.destroy
    redirect_to(team_roster_index_path)
  end
  

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :class_year, :email, :phone)
    end
  end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @student = Student.order('id ASC')
    @event = Event.order('id ASC')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash.notice = "event created"
      redirect_to(event_index_path)
    else
      render('new')
    end
  end

  def show
    @event = Event.find(params[:id])
    commitments = Commitment.where(event_id: @event.id)
    student_ids = Array.new
    commitments.each do |commitment|
      student_ids.push(commitment.student_id)
    end

    @students = Array.new
    student_ids.each do |student_id|
      @students.push(Student.where(id: student_id).first)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash.notice = "event updated"
      redirect_to(event_path(@event))
    else
      render("edit")
    end
  end

  def delete
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to(event_index_path)
  end
  

  private
    def event_params
      params.require(:event).permit(:event_id, :event_name, :event_type, :date_time, :location, :description)
    end

    def helper_params
      params.permit(:event_id, :event_name, :event_type, :date_time, :location, :description)
    end
    
  end

app/controllers/team_roster_controller.rb
class TeamRosterController < ApplicationController
  def index
    @student = Student.order('id ASC')
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash.notice = "Student created"
      redirect_to(team_roster_index_path)
    else
      render('new')
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash.notice = "Student updated"
      redirect_to(team_roster_path(@student))
    else
      render("edit")
    end
  end

  def delete
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(team_roster_index_path)
  end
  

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :class_year, :email, :phone)
    end
  end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/calendar.html.erb
<h1>Admin#calendar</h1>
<p>Find me in app/views/admin/calendar.html.erb</p>

app/views/admin/commitment.html.erb
<h1>Admin#commitment</h1>
<p>Find me in app/views/admin/commitment.html.erb</p>

app/views/admin/event.html.erb
<h1>Admin#event</h1>
<p>Find me in app/views/admin/event.html.erb</p>

app/views/admin/team_roster.html.erb
<h1>Admin#team_roster</h1>
<p>Find me in app/views/admin/team_roster.html.erb</p>

app/views/calendar/delete.html.erb
<%#= link_to("<< Back to team roster", team_roster_index_path, :class => 'back-link') %>

<!--<div class="team roster new">-->
<!--  <h2>Delete member</h2>-->

  <%#= form_for(@student, :url => team_roster_path, :method => 'delete') do |f| %>

<!--    <p>Are you sure you want to permanently delete this member? </p>-->

<!--    <table summary="book form fields">-->
<!--        <tr>-->
<!--            <th>First name</th>-->
<!--            <td><%#= @student.first_name %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Last name</th>-->
<!--            <td><%#= @student.last_name %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Class year</th>-->
<!--            <td><%#= @student.class_year %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Email</th>-->
<!--            <td><%#= @student.email %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Phone number</th>-->
<!--            <td><%#= @student.phone %></td>-->
<!--        </tr>-->

<!--    </table>-->

<!--    <div class="form-buttons">-->
      <%#= f.submit("Delete student") %>
<!--    </div>-->

  <%# end %>
<!--</div>-->
<%= month_calendar do |date| %>
  <%= date %>
<% end %>

app/views/calendar/edit.html.erb
<%= link_to('Back', 'javascript:history.back()') %>
<div class="team roster new">
  <h2>Update member</h2>

  <%= form_for(@student, :url => team_roster_path, :method => 'patch') do |f| %>

    <table summary="students form fields">
        <tr>
            <th>First name</th>
            <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= f.text_field(:class_year) %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= f.text_field(:email) %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= f.text_field(:phone) %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Update student") %>
    </div>

  <% end %>
</div>

app/views/calendar/index.html.erb
<%= link_to("team roster", team_roster_index_path , :class => 'action new') %>
<%= link_to("event", event_index_path , :class => 'action new') %>


<%= month_calendar(events: @meetings, attribute: :date_time) do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div>
      <a href="/event/<%= meeting.id %>"><%= meeting.event_name %></a>
    </div>
  <% end %>
<% end %>

app/views/calendar/new.html.erb
<%= link_to('Back', 'javascript:history.back()') %>
<div class="team roster new">
  <h2>Create member</h2>

  <%= form_for(@student, :url => team_roster_index_path, :method => 'post') do |f| %>

    <table summary="book form fields">
        <tr>
            <th>First name</th>
            <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= f.text_field(:class_year) %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= f.text_field(:email) %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= f.text_field(:phone) %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Create new student") %>
    </div>

  <% end %>
</div>

app/views/calendar/show.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<!--<div class="team roster new">-->
<!--  <h2>Update member</h2>-->

  <%#= form_for(team_roster_index_path) do |f| %>

<!--    <table summary="book form fields">-->
<!--        <tr>-->
<!--            <th>First name</th>-->
<!--            <td><%#= @student.first_name %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Last name</th>-->
<!--            <td><%#= @student.last_name %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Class year</th>-->
<!--            <td><%#= @student.class_year %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Email</th>-->
<!--            <td><%#= @student.email %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Phone number</th>-->
<!--            <td><%#= @student.phone %></td>-->
<!--        </tr>-->

<!--    </table>-->

  <%# end %>

<!--</div>-->
<!--<div class="row">-->
<!--  <div class="col-md-12 text-center">-->
<!--    <div class="well controls">-->
      <%#= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
<!--        <i class="glyphicon glyphicon-backward"></i>-->
      <%# end %>
      <%#= "#{@date.strftime("%B")} #{@date.year}" %>
      <%#= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
<!--        <i class="glyphicon glyphicon-forward"></i>-->
      <%# end %>
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="row">-->
<!--  <div class="col-md-12">-->
    <%#= calendar @date do |date| %>
      <%#= date.day %>
    <%# end %>
<!--  </div>-->
<!--</div>-->

app/views/commitment/delete.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div class="team roster new">
  <h2>Delete member</h2>

  <%= form_for(@commitment, :url => commitment_path(@student), :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this commitment? </p>

    <table summary="book form fields">
        <tr>
            <th>First name</th>
            <td><%= @student.first_name %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= @student.last_name %></td>
        </tr>
        <tr>
            <th>Event</th>
            <td><%= @event.event_name %></td>

        </tr>
      <%=f.hidden_field :commitment_id, value: @commitment.id %>


    </table>

    <div class="form-buttons">
      <%= f.submit("Delete Commitment") %>
    </div>

  <% end %>
</div>

app/views/commitment/edit.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div class="team roster new">
  <h2>Update member</h2>

  <%= form_for(@commitment, :url => commitment_path(@student), :method => 'patch') do |f| %>

    <table summary="students form fields">
        <tr>
          <th>First name</th>
          <td><%= @student.first_name %></td>
        </tr>
        <tr>
          <th>Last name</th>
          <td><%= @student.last_name %></td>
        </tr>
        <tr>
          <th>Event</th>
          <th><%= f.select :id, @events.map { |e| [e.event_name, e.id]} %></th>

        </tr>

    </table>
    <%=f.hidden_field :commitment_id, value: @commitment.id %>

    <div class="form-buttons">
      <%= f.submit("Update Commitment") %>
    </div>

  <% end %>
</div>

app/views/commitment/index.html.erb
<%= link_to("team roster", team_roster_index_path , :class => 'action new') %>
<%= link_to("calendar", calendar_index_path , :class => 'action new') %>
<%= link_to("event", event_index_path , :class => 'action new') %>

<div>
<h2>Commitment</h2>

<%#= link_to("Add New Commitment", commitment_path(student), class: 'action new') %>
  <a href="/commitment/new/<%= student.id %>">Add New Commitment</a>
    <h2><%= @student.first_name %>'s Commitments</h2>

      <table>
        <tr class="header">
          <th>#</th>
          <th>Event Name</th>
          <th>View Details</th>
        </tr>
        <% @commitments.each do |commitment| %>
        <tr>
          <td><%= commitment.event.id %></td>
          <td><%= commitment.event.event_name %></td>
          <td><%= link_to('Event Page', {controller: 'event', action: 'index', id: commitment.event.id}) %></td>
<!--          <td><%#= link_to 'event', commitment_path(commitment.event.id) %></td>-->

        </tr>
        <% end %>
      </table>
</div>

app/views/commitment/new.html.erb
<%= link_to("<< Back to team roster", commitment_index_path, :class => 'back-link') %>

<div class="team roster new">
  <h2>Create Commitment</h2>

  <%= form_for(@event, :url => commitment_index_path, :method => 'post') do |f| %>

    <table summary="book form fields">
      <tr><th>First name: <%=@student.first_name %>  </th></tr><br>
      <tr><th>Last name: <%=@student.last_name %></th></tr>

      <%=f.hidden_field :student_id, value: @student.id %>
<!--        <tr>-->
<!--            <th>First name</th>-->
<!--            <td><%#= f.text_field(:) %></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>Last name</th>-->
<!--            <td><%#= f.text_field(:last_name) %></td>-->
<!--        </tr>-->
      <%# form_with(scope: "events") do |f| %>
        <%#= f.text_field :name %>
      <tr><th><%= f.select :id, @events.map { |e| [e.event_name, e.id]} %></th></tr>
      <%#= f.submit %>
        <%# end %>


    </table>


    <div class="form-buttons">
      <%= f.submit("Create new commitment") %>
    </div>

  <% end %>
</div>

app/views/commitment/show.html.erb
<%= link_to("team roster", team_roster_index_path , :class => 'action new') %>
<%= link_to("calendar", calendar_index_path , :class => 'action new') %>
<%= link_to("event", event_index_path , :class => 'action new') %>

<div>
<h2>Commitment</h2>

<%#= link_to("Add New Commitment", new_commitment_path , :class => 'action new') %>
  <a href="/commitment/new?id=<%= @student.id %>">Add New Commitment</a>

  <h2><%= @student.first_name %>'s Commitments</h2>

      <table>
        <tr class="header">
          <th>#</th>
          <th>Event Name</th>
          <th>View Details</th>
        </tr>
        <% @commitments.each do |commitment| %>
        <tr>
          <td><%= commitment.event.id %></td>
          <td><%= commitment.event.event_name %></td>
          <td class="actions">
            <%= link_to('Event Page', {controller: 'event', action: 'index', id: commitment.event.id}) %>
            <%= link_to('Edit', {controller: 'commitment', action: 'edit', id: commitment.id}) %>
            <%= link_to('Delete', {controller: 'commitment', action: 'delete', id: commitment.id}) %>
          </td>
        </tr>
        <% end %>
      </table>
</div>

app/views/event/delete.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div class="team roster new">
  <h2>Delete member</h2>

  <%= form_for(@student, :url => event_index_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this member? </p>

    <table summary="book form fields">
        <tr>
            <th>First name</th>
            <td><%= @student.first_name %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= @student.last_name %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= @student.class_year %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= @student.email %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= @student.phone %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Delete student") %>
    </div>

  <% end %>
</div>

app/views/event/edit.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div class="team roster new">
  <h2>Update member</h2>

  <%= form_for(@student, :url => event_index_path, :method => 'patch') do |f| %>

    <table summary="students form fields">
        <tr>
            <th>First name</th>
            <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= f.text_field(:class_year) %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= f.text_field(:email) %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= f.text_field(:phone) %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Update student") %>
    </div>

  <% end %>
</div>

app/views/event/index.html.erb
<%= link_to("team roster", team_roster_index_path , :class => 'action new') %>
<%= link_to("calendar", calendar_index_path , :class => 'action new') %>

<div>
  <h2>Event</h2>

  <%= link_to("Add New Event", new_event_path , :class => 'action new') %>

  <table>
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Type</th>
      <th>Date</th>
      <th>Description</th>
      <th>Location</th>
    </tr>
    <% @event.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.event_name %></td>
        <td><%= event.event_type %></td>
        <td><%= event.date_time %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td class="actions"> 
        <%= link_to("Show", event_path(event), :class => 'action show') %> 
      </td>
      </tr>
    <% end %>
  </table>
  
</div>

app/views/event/new.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div class="team roster new">
  <h2>Create Event</h2>

  <%= form_for(@event, :url => event_index_path, :method => 'post') do |f| %>

    <table summary="book form fields">
        <tr>
            <th>Event name</th>
            <td><%= f.text_field(:event_name) %></td>
        </tr>
        <tr>
            <th>Event type</th>
            <td><%= f.text_field(:event_type) %></td>
        </tr>
        <tr>
            <th>Date time</th>
            <td><%= f.text_field(:date_time) %></td>
        </tr>
        <tr>
            <th>location</th>
            <td><%= f.text_field(:location) %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= f.text_field(:description) %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Create new event") %>
    </div>

  <% end %>
</div>

app/views/event/show.html.erb
<%= link_to('Back', 'javascript:history.back()') %>

<div>
<%= form_for(team_roster_index_path) do |f| %>
  <h2>Students Signed Up For <%= @event.event_name %></h2>

  <table>
    <tr class="header">
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Commitments</th>
    </tr>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.id %></td>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><a href="/commitment/<%=student.id %>">View</a></td>
<!--      <td><%#= link_to("View", controller: 'commitment', action: 'index', id: student.id) %></td>-->
    </tr>
    <% end %>
  </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T12App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
    <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--  <title>CalendarExample</title>-->
  <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%#= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%#= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%#= csrf_meta_tags %>
<!--</head>-->
<!--<body>-->
<!--<div class="container">-->
  <%#= yield %>
<!--</div>-->

<!--</body>-->
<!--</html>-->

app/views/team_roster/delete.html.erb
<%= link_to('Back', 'javascript:history.back()') %>
<div class="team roster new">
  <h2>Delete member</h2>

  <%= form_for(@student, :url => team_roster_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this member? </p>

    <table summary="book form fields">
        <tr>
            <th>First name</th>
            <td><%= @student.first_name %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= @student.last_name %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= @student.class_year %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= @student.email %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= @student.phone %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Delete student") %>
    </div>

  <% end %>
</div>

app/views/team_roster/edit.html.erb
<%= link_to('Back', 'javascript:history.back()') %>
<div class="team roster new">
  <h2>Update member</h2>

  <%= form_for(@student, :url => team_roster_path, :method => 'patch') do |f| %>

    <table summary="students form fields">
        <tr>
            <th>First name</th>
            <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
            <th>Last name</th>
            <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
            <th>Class year</th>
            <td><%= f.text_field(:class_year) %></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= f.text_field(:email) %></td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td><%= f.text_field(:phone) %></td>
        </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Update student") %>
    </div>

  <% end %>
</div>

app/views/team_roster/index.html.erb
<%= link_to("Calendar", calendar_index_path , :class => 'action new') %>
<%= link_to("event", event_index_path , :class => 'action new') %>

<div>
  <h2>Team Roster</h2>

   <%= link_to("Add New Student", new_team_roster_path , :class => 'action new') %>

  <table>
    <tr class="header">
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Class Year</th>
      <th>A&M Eamil</th>
      <th>Phone Number</th>
    </tr>
    <% @student.each do |student| %>
    <tr>
      <td><%= student.id %></td>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><%= student.class_year %></td>
      <td><%= student.email %></td>
      <td><%= student.phone %></td>
      <td class="actions"> 
        <%= link_to("Show Commitments", commitment_path(student), class: 'action show') %>
        <%= link_to("Edit", edit_team_roster_path(student), :class => 'action edit') %>
        <%= link_to("Delete", delete_team_roster_path(student), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/user/calendar.html.erb
<h1>User#calendar</h1>
<%# <%= link_to('Commitment Page', {controller: 'user', action: 'commitment'}) %> %>
<%= link_to('Team Roster Page', {controller: 'user', action: 'team_roster'}) %>
<%= month_calendar do |date| %>
  <%= date %>
<% end %>